language: node_js
sudo: false
node_js:
- '4'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_3e0a95143fa0_key -iv $encrypted_3e0a95143fa0_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'raykr'
- git config --global user.email ray_kr@163.com
install:
- npm install hexo-cli -g
- npm install
script:
- npm run deploy
notifications:
  slack:
    secure: rH+xqmNeW6x46ykA5jM3mphkEGvLL1+BVaIwu8wVm67XGzldcbSGXcQjN6YQyx0ThnlaXqjug3VuL/iDDLNRTikzgJODSjML9KFU1icTb5SNsIsOcKA91nIjrh3pO+Wu40PQjjGYz6CKxtCuO+7gYfXBrzkahc5Yukz3KzhV2DsbnI3lu/XHak7pVmyCrkZsT+dfWbIW78iGCYoVJ/83109FVtIsD5hDLsVAMs2o161LPqIpMoyRvxAsOzHN3vBrpi8+XnB+x3N4bSdYRVtNAXpQPYkYQXjeNRP5FXP/4cmAj1NkXlKplvFN1mn09VkTCDEvOfj1I7yg3zAw/YZUhMEQYwlLvn0nTngJ7CHIHYLYBOWmzJB1QDDgK1kTbknXoifrDdXePI0CS/SedSjXRDPZ0ufJcnleob6md0brIH++5AEth2Zbk/DyT5+9f5ASHJLLEB7aFHmqkDT4KS+DdXSioiBerGkil/o073/Kqv2wx8s0bC9EcPZuu9EO+VtH4xejpVv/rSw/oVhaE5Dfy1qCHqJIha0gbXdpGGXQFWMUa56fnORCEAGiI5EBS7FbIkkbKKPgnw2rkv69kH6j4H2EiILPHRYddNUXpTo7Eh3z+S3cpRna8ztTgVeMF5Mj4hGcEbaWth+gjH8ewExLHYkB9BfvbBAn3KqlLKkuuzQ=
